server:
  host: 0.0.0.0
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/limits_service
    username: root
    password: password
  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/limits_service
  show-sql: true